// ============================================================
// Battery_Holder_tunable.scad
// Generated by Battery Holder Designer
//
// The battery and screw hardware are reference geometry only.
// They appear in preview when enabled but are not exported.
// ============================================================

$fn = 96;

// ---------------- HOLDER ----------------
overall_w = 61.2827;
overall_d = 64.1609;
overall_h = 5.9252;

floor_t = 0.44385;
wall_h = 5.18313;
flange_t = 0.765216;
tray_wall_t = 1;
flange_z = overall_h - flange_t;

// ---------------- BATTERY / POCKET ----------------
battery_w = 48;
battery_d = 57;
battery_h = 5;
clearance_x = 0.5;
clearance_y = 0.5;
battery_offset_x = 0;
battery_offset_y = 0;

pocket_w = battery_w + clearance_x * 2;
pocket_d = battery_d + clearance_y * 2;
pocket_x0 = battery_offset_x - pocket_w / 2;
pocket_y0 = battery_offset_y - pocket_d / 2;

// ---------------- SCREW PATTERN ----------------
hole_pitch_x = 58;
hole_pitch_y = 49;
hole_d = 2.41639;
underside_hardware_d = 5.4;
hardware_reference_h = 6;

hole_x = hole_pitch_x / 2;
hole_y = hole_pitch_y / 2;
hole_positions = [
    [-hole_x, -hole_y],
    [ hole_x, -hole_y],
    [-hole_x,  hole_y],
    [ hole_x,  hole_y]
];

// ---------------- OPENINGS ----------------
// Rear opening is cut in from +Y edge and through the rear tray wall.
rear_notch_w = 9.17705;
rear_notch_x = -15.5;
rear_notch_extra_into_pocket = 1.25;

// Side opening is cut in from -X edge and through the left tray wall.
side_notch_d = 11.9299;
side_notch_y = -10.5;
side_notch_extra_into_pocket = 1.25;

// ---------------- PREVIEW REFERENCES ----------------
show_battery_reference = true;
show_hardware_references = true;
show_original_stl = false;
original_stl_path = "";
stl_scale = 1000;
stl_translate = [0, 0, 0];
stl_rotate = [0, 0, 0];

// ============================================================
// CUTTERS
// ============================================================

module mounting_hole(x, y) {
    translate([x, y, flange_z - 0.1])
        cylinder(h = flange_t + 0.3, d = hole_d);
}

module rear_notch_cut(z_start = floor_t, cut_h = overall_h + 1) {
    translate([
        rear_notch_x - rear_notch_w / 2,
        pocket_y0 + pocket_d - tray_wall_t - 0.01,
        z_start
    ])
        cube([
            rear_notch_w,
            overall_d / 2 - (pocket_y0 + pocket_d)
                + tray_wall_t + rear_notch_extra_into_pocket + 0.02,
            cut_h
        ]);
}

module side_notch_cut(z_start = floor_t, cut_h = overall_h + 1) {
    translate([
        -overall_w / 2 - 0.01,
        side_notch_y - side_notch_d / 2,
        z_start
    ])
        cube([
            pocket_x0 - (-overall_w / 2)
                + tray_wall_t + side_notch_extra_into_pocket + 0.02,
            side_notch_d,
            cut_h
        ]);
}

// ============================================================
// HOLDER GEOMETRY
// ============================================================

module battery_floor() {
    translate([pocket_x0, pocket_y0, 0])
        cube([pocket_w, pocket_d, floor_t]);
}

module tray_walls_uncut() {
    difference() {
        translate([
            pocket_x0 - tray_wall_t,
            pocket_y0 - tray_wall_t,
            0
        ])
            cube([
                pocket_w + tray_wall_t * 2,
                pocket_d + tray_wall_t * 2,
                wall_h
            ]);

        translate([pocket_x0, pocket_y0, floor_t])
            cube([pocket_w, pocket_d, wall_h + 1]);
    }
}

module tray_walls() {
    difference() {
        tray_walls_uncut();

        // BOTH openings cut through the supporting vertical tray walls.
        rear_notch_cut();
        side_notch_cut();
    }
}

module top_flange() {
    difference() {
        translate([-overall_w/2, -overall_d/2, flange_z])
            cube([overall_w, overall_d, flange_t]);

        translate([pocket_x0, pocket_y0, flange_z - 0.1])
            cube([pocket_w, pocket_d, flange_t + 0.3]);

        // BOTH openings cut through the top flange.
        rear_notch_cut(flange_z - 0.1, flange_t + 0.3);
        side_notch_cut(flange_z - 0.1, flange_t + 0.3);

        for (pos = hole_positions)
            mounting_hole(pos[0], pos[1]);
    }
}

module battery_holder() {
    union() {
        battery_floor();
        tray_walls();
        top_flange();
    }
}

// ============================================================
// PREVIEW-ONLY REFERENCE GEOMETRY
// ============================================================

module battery_reference() {
    %color("DodgerBlue", 0.35)
        translate([
            battery_offset_x - battery_w/2,
            battery_offset_y - battery_d/2,
            floor_t
        ])
            cube([battery_w, battery_d, battery_h]);
}

module hardware_references() {
    for (pos = hole_positions) {
        %color("Crimson", 0.45)
            translate([pos[0], pos[1], flange_z - hardware_reference_h])
                cylinder(h = hardware_reference_h, d = underside_hardware_d);
    }
}

module original_stl_reference() {
    if (original_stl_path != "")
        %color("LimeGreen", 0.22)
            translate(stl_translate)
                rotate(stl_rotate)
                    scale([stl_scale, stl_scale, stl_scale])
                        import(original_stl_path, convexity = 10);
}

// ============================================================
// OUTPUT
// ============================================================

battery_holder();

if (show_battery_reference)
    battery_reference();

if (show_hardware_references)
    hardware_references();

if (show_original_stl)
    original_stl_reference();
